using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class Level6Controller : BaseLevelController
{
    public override void SetLogicString()
    {
         _wire_list =
             "InputSwitch1 _out AndGate1 a " +
             "InputSwitch1 _out Inverter1 a " +
             "Inverter1 _out AndGate1 b " +
             "AndGate1 _out LightBulb a";
        SetHintString("Glitch generated by converged inverted paths");
        // Debug.Log("In SLS L6C,  _wire_list = " +  _wire_list);
    }
}
